### ISSUE TITLE
#{pastize(action)}_by?(source)

### ISSUE THREAD

**Issue by shohey1226** [kami30k/acts_as_relationship#1]
Hi, thanks for sharing great gem.

I have quick question.

https://github.com/kami30k/acts_in_relation/blob/master/lib/acts_in_relation/roles/target.rb#L17

Should this be the following? 

```
source.#{action.pluralize}.exists?("target_#{target}_id: target.id)
```

**Comment by zenizh** [comment]
@shohey1226 Thank you for your comment!
I have checked the code again, and finally I conclude that it should be following:

``` ruby
def #{pastize(action)}_by?(source)
  source.#{action.pluralize}.exists?(target_#{target}_id: id) # not `target.id`
end
```

What do you think about this?
If you agree with it, please send me a pull request, or I'll do it myself later.

Thanks!

**Comment by shohey1226** [comment]
Thanks for quick response. ya, agree.  just send a PR for this.

**Comment by zenizh** [comment]
@shohey1226 Thank you for your contribution! :tada:
