### ISSUE TITLE
can not specify the resource name that underscores enter

### ISSUE THREAD

**Issue by jikuya** [kami30k/acts_as_relationship#4]
The following as `_` is not can not specify the resource name to enter .
`resonate :user,    with: :project, by: :favorite_comment, foreign_key: :comment_id`

But to work if you use the `classify` in the following line, What's a reason you're using `capitalize`?
https://github.com/kami-zh/resonance/blob/master/lib/resonance/supports/converter.rb#L9

**Comment by zenizh** [comment]
@jikuya Sorry for late reply because of having a big earthquake in Kumamoto 🙇 
I think this issue has improved by #5 .

**Comment by zenizh** [comment]
Please re-post this issue if this has not resolved 🙏

**Comment by jikuya** [comment]
Thank you for your reply.
It is works for me.
Thanks for support.
